#ifndef PLATFORMERSFML_STATEENUM_H
#define PLATFORMERSFML_STATEENUM_H

enum class GameStates
{
  MAIN_MENU,
  LEVEL_SELECTOR,
  IN_GAME,
  GAME_OVER,
  GAME_WIN,
  TUTORIAL,
};

#endif // PLATFORMERSFML_STATEENUM_H
